Entry.create(title: "Find Your Way Home", content: "I'm baby fanny pack shabby chic listicle, hot chicken williamsburg hoodie yr austin enamel pin kinfolk selvage sustainable leggings taxidermy. Direct trade church-key edison bulb hexagon, trust fund lyft leggings unicorn pop-up iceland taxidermy salvia activated charcoal single-origin coffee woke. Brooklyn kombucha truffaut typewriter, tbh austin wayfarers asymmetrical lumbersexual DIY squid poutine single-origin coffee cred. Aesthetic polaroid man braid lo-fi, viral skateboard hammock vinyl try-hard farm-to-table echo park microdosing edison bulb craft beer banh mi. Vice echo park woke disrupt, raclette tousled marfa tofu photo booth fingerstache sartorial live-edge. Chicharrones ethical yuccie iPhone, everyday carry biodiesel tofu before they sold out celiac taxidermy austin. Pug vaporware single-origin coffee messenger bag jianbing gluten-free intelligentsia seitan.

Asymmetrical mustache pabst put a bird on it mumblecore flannel bespoke ennui lyft cray la croix cloud bread salvia vegan edison bulb. Ethical cliche selfies photo booth, portland shaman neutra lyft gochujang heirloom trust fund readymade. Listicle tilde activated charcoal authentic. Cliche succulents poke, iPhone food truck meditation celiac. Butcher authentic stumptown, godard adaptogen palo santo 3 wolf moon swag edison bulb letterpress thundercats taxidermy. Vinyl pinterest synth brooklyn cardigan.

3 wolf moon YOLO tbh, four dollar toast snackwave cred sartorial plaid adaptogen microdosing leggings hella bushwick post-ironic kale chips. Lyft irony actually, pork belly you probably haven't heard of them gochujang cray fashion axe williamsburg synth tote bag thundercats. Scenester kickstarter try-hard heirloom keytar sriracha asymmetrical vegan snackwave tumblr. Chia gastropub hashtag cloud bread wolf fashion axe kogi.

Yuccie chicharrones mumblecore hell of cred cliche beard gastropub direct trade craft beer marfa quinoa four dollar toast. Stumptown small batch umami photo booth brunch. Kinfolk vice biodiesel, snackwave retro DIY food truck tbh mustache freegan fixie. Heirloom mixtape vape XOXO typewriter banh mi intelligentsia. Hashtag whatever raclette synth edison bulb.

Everyday carry aesthetic franzen flexitarian narwhal listicle viral. Shoreditch lumbersexual whatever godard, raw denim etsy twee. Iceland semiotics master cleanse try-hard normcore. Palo santo thundercats lumbersexual swag. Gochujang photo booth raw denim tattooed microdosing twee food truck, woke lomo tote bag. Tote bag gluten-free mlkshk lomo, tofu VHS pok pok fam chillwave man braid hashtag hot chicken.", author_name: "Erin Schallmoser", author_bio: "Irony post-ironic snackwave, drinking vinegar glossier narwhal neutra. Bicycle rights edison bulb meh, helvetica next level pok pok single-origin coffee raw denim shaman iceland aesthetic adaptogen marfa. Messenger bag knausgaard vape artisan pinterest echo park asymmetrical craft beer tbh. Hell of authentic sustainable lo-fi narwhal echo park. 3 wolf moon tote bag enamel pin lyft, four dollar toast wolf blue bottle. Umami hot chicken cold-pressed unicorn viral truffaut.", image: "https://live.staticflickr.com/175/467428478_5bc4dda4d5_b.jpg")

Entry.create(title: "Running In Place", content: "Hexagon crucifix tote bag, venmo freegan before they sold out XOXO raclette put a bird on it bicycle rights tofu blue bottle hashtag. Vexillologist art party twee chartreuse. Single-origin coffee mustache raclette swag shabby chic normcore. Swag ugh you probably haven't heard of them, salvia fanny pack tacos umami selvage. Adaptogen post-ironic hoodie small batch wolf pug plaid meh fanny pack normcore cardigan iceland lo-fi paleo tumeric. Gochujang heirloom meh hashtag ugh.

Venmo stumptown sustainable pinterest man braid bespoke umami beard blog iceland flexitarian. Hot chicken you probably haven't heard of them normcore artisan offal bicycle rights, tacos narwhal vape yr +1 shabby chic single-origin coffee. Food truck roof party chillwave, health goth PBR&B jean shorts succulents franzen unicorn chartreuse truffaut farm-to-table. Pitchfork ennui enamel pin 90's.

Jean shorts selvage gentrify everyday carry artisan. Butcher selvage disrupt vegan meggings occupy bespoke cardigan. Humblebrag adaptogen pitchfork, freegan umami pabst mustache dreamcatcher. Humblebrag church-key hashtag air plant vape tousled sustainable aesthetic forage. Blue bottle iceland 8-bit woke, jianbing +1 truffaut yr YOLO snackwave tbh vaporware heirloom. Retro hell of chicharrones, ugh poke adaptogen helvetica viral hot chicken master cleanse palo santo.

Literally narwhal iPhone vaporware XOXO truffaut try-hard 8-bit meh austin neutra YOLO. Man braid gochujang blue bottle health goth, XOXO biodiesel synth flannel bespoke farm-to-table iPhone. Shabby chic tumblr prism beard literally, tofu DIY wayfarers. Hot chicken dreamcatcher bitters gluten-free, banh mi letterpress flannel wolf enamel pin tbh jean shorts. Banjo meggings man bun shoreditch tacos hot chicken. Aesthetic poke pork belly tumeric. Blog forage chillwave, vice church-key try-hard direct trade hashtag health goth offal lo-fi slow-carb echo park marfa actually.", author_name: "Doug Schallmoser", author_bio: "Distillery yuccie blog locavore. Hoodie mumblecore pop-up, helvetica ugh pabst sartorial. Ugh seitan DIY hot chicken truffaut. Flexitarian heirloom photo booth freegan kale chips meditation. Before they sold out semiotics 90's poke hexagon four loko pok pok freegan. Ramps green juice aesthetic freegan venmo 3 wolf moon tilde man braid pickled cloud bread PBR&B hell of franzen.", image: "https://www.exploreminnesota.com/sites/default/files/styles/share_image/public/2019-10/grand-marais-honeymoon-bluff-woman-hiking_roy-son.jpg")

Entry.create(title: "Simplicity Sake", content: "I'm baby fanny pack shabby chic listicle, hot chicken williamsburg hoodie yr austin enamel pin kinfolk selvage sustainable leggings taxidermy. Direct trade church-key edison bulb hexagon, trust fund lyft leggings unicorn pop-up iceland taxidermy salvia activated charcoal single-origin coffee woke. Brooklyn kombucha truffaut typewriter, tbh austin wayfarers asymmetrical lumbersexual DIY squid poutine single-origin coffee cred. Aesthetic polaroid man braid lo-fi, viral skateboard hammock vinyl try-hard farm-to-table echo park microdosing edison bulb craft beer banh mi. Vice echo park woke disrupt, raclette tousled marfa tofu photo booth fingerstache sartorial live-edge. Chicharrones ethical yuccie iPhone, everyday carry biodiesel tofu before they sold out celiac taxidermy austin. Pug vaporware single-origin coffee messenger bag jianbing gluten-free intelligentsia seitan.

Asymmetrical mustache pabst put a bird on it mumblecore flannel bespoke ennui lyft cray la croix cloud bread salvia vegan edison bulb. Ethical cliche selfies photo booth, portland shaman neutra lyft gochujang heirloom trust fund readymade. Listicle tilde activated charcoal authentic. Cliche succulents poke, iPhone food truck meditation celiac. Butcher authentic stumptown, godard adaptogen palo santo 3 wolf moon swag edison bulb letterpress thundercats taxidermy. Vinyl pinterest synth brooklyn cardigan.

3 wolf moon YOLO tbh, four dollar toast snackwave cred sartorial plaid adaptogen microdosing leggings hella bushwick post-ironic kale chips. Lyft irony actually, pork belly you probably haven't heard of them gochujang cray fashion axe williamsburg synth tote bag thundercats. Scenester kickstarter try-hard heirloom keytar sriracha asymmetrical vegan snackwave tumblr. Chia gastropub hashtag cloud bread wolf fashion axe kogi.

Yuccie chicharrones mumblecore hell of cred cliche beard gastropub direct trade craft beer marfa quinoa four dollar toast. Stumptown small batch umami photo booth brunch. Kinfolk vice biodiesel, snackwave retro DIY food truck tbh mustache freegan fixie. Heirloom mixtape vape XOXO typewriter banh mi intelligentsia. Hashtag whatever raclette synth edison bulb.

Everyday carry aesthetic franzen flexitarian narwhal listicle viral. Shoreditch lumbersexual whatever godard, raw denim etsy twee. Iceland semiotics master cleanse try-hard normcore. Palo santo thundercats lumbersexual swag. Gochujang photo booth raw denim tattooed microdosing twee food truck, woke lomo tote bag. Tote bag gluten-free mlkshk lomo, tofu VHS pok pok fam chillwave man braid hashtag hot chicken.", author_name: "Dwight Schrute", author_bio: "Distillery yuccie blog locavore. Hoodie mumblecore pop-up, helvetica ugh pabst sartorial. Ugh seitan DIY hot chicken truffaut. Flexitarian heirloom photo booth freegan kale chips meditation. Before they sold out semiotics 90's poke hexagon four loko pok pok freegan. Ramps green juice aesthetic freegan venmo 3 wolf moon tilde man braid pickled cloud bread PBR&B hell of franzen.", image: "https://www.dgs.udel.edu/sites/default/files/styles/max_650x650/public/geohydro/fossils-orange_slug.jpg")

Entry.create(title: "Woods and Glaciers", content: "I'm baby coloring book next level authentic mumblecore hexagon. Try-hard listicle enamel pin, mixtape slow-carb squid hammock polaroid retro celiac sriracha tbh af. Raclette freegan taxidermy next level vinyl messenger bag. Bushwick stumptown yr, poutine plaid locavore schlitz glossier live-edge scenester.

Four loko taiyaki poutine health goth. Humblebrag distillery tattooed woke tumeric godard tbh cronut tilde health goth. Literally flexitarian offal farm-to-table squid, knausgaard schlitz brunch. Chillwave tofu pug keffiyeh shabby chic tumeric offal taiyaki health goth sartorial bicycle rights. Taxidermy artisan four dollar toast la croix, bushwick trust fund kickstarter live-edge kitsch ramps vegan gochujang. Lyft cray subway tile banjo la croix next level.

Four dollar toast jianbing butcher, godard hammock raclette flannel pickled irony wolf church-key cornhole fixie quinoa. Schlitz tbh edison bulb, tofu chicharrones blue bottle pok pok lo-fi hell of. Pinterest helvetica edison bulb cray literally freegan before they sold out you probably haven't heard of them keytar art party pour-over trust fund. Listicle XOXO narwhal celiac yuccie. Direct trade semiotics cornhole glossier mlkshk migas irony. Hell of bitters biodiesel fashion axe put a bird on it jianbing next level echo park butcher.

Kale chips listicle enamel pin biodiesel salvia hammock. Church-key kombucha art party, meditation lo-fi hashtag 90's gentrify la croix. Single-origin coffee pok pok distillery cred, swag franzen gentrify cliche kombucha. Iceland schlitz deep v iPhone retro selvage, pinterest venmo normcore banjo wayfarers actually gastropub. Vice franzen portland meh cornhole vaporware.

Pok pok next level locavore mumblecore keffiyeh hexagon sustainable yuccie cornhole ramps prism iPhone skateboard. Af banjo wolf hella meggings sriracha marfa food truck gluten-free church-key plaid bespoke. Tbh mumblecore listicle kombucha, scenester edison bulb iPhone freegan activated charcoal brooklyn cliche plaid. Godard direct trade glossier 90's YOLO typewriter tote bag occupy kogi lyft wayfarers. Lomo kogi echo park, normcore tofu flannel +1 gochujang ennui everyday carry disrupt four dollar toast stumptown dreamcatcher. Forage farm-to-table ennui knausgaard paleo portland 8-bit.

Ennui cloud bread semiotics cold-pressed, hella vaporware drinking vinegar farm-to-table whatever shaman plaid skateboard portland helvetica. Shaman vinyl yr edison bulb, whatever tousled kale chips you probably haven't heard of them taxidermy four loko seitan la croix iPhone microdosing poke. Ennui kale chips 3 wolf moon, bespoke forage twee brunch pour-over. Activated charcoal chillwave retro street art squid meh. Organic kinfolk trust fund tumblr.

Cronut before they sold out try-hard sustainable knausgaard. Vinyl offal pour-over, copper mug vegan austin jianbing kombucha keytar. Hashtag chicharrones green juice celiac put a bird on it pitchfork. Meggings la croix knausgaard, twee hella migas chicharrones umami. 3 wolf moon shabby chic tilde, ugh thundercats etsy affogato ramps keytar locavore man braid actually scenester literally hella. Wolf four loko man braid craft beer, cornhole green juice poutine tofu hammock bitters literally tote bag church-key. Tote bag XOXO jean shorts leggings, palo santo literally lyft synth normcore.

Humblebrag direct trade palo santo pork belly. Four dollar toast food truck tilde disrupt. Fingerstache 90's beard actually, kogi aesthetic hammock kombucha banjo cloud bread pop-up. Semiotics shabby chic tbh before they sold out pabst yr roof party pour-over sartorial mumblecore humblebrag. Pork belly meditation cloud bread, selvage woke waistcoat chillwave tote bag sartorial vexillologist microdosing chartreuse. Retro 90's tumeric ennui health goth typewriter poutine iceland schlitz. Blog intelligentsia trust fund cornhole, typewriter forage everyday carry.", author_name: "Robert California", author_bio: "Blog chillwave asymmetrical chartreuse wolf pork belly kale chips 3 wolf moon YOLO gochujang hell of. Vaporware 3 wolf moon shoreditch, hell of four loko ethical fashion axe bushwick keffiyeh vegan. Stumptown swag slow-carb fixie chillwave master cleanse. Jean shorts knausgaard cardigan, venmo cloud bread keffiyeh taxidermy. Selvage ennui waistcoat roof party tumblr.", image: "https://www.bethelwoodscenter.org/sites/default/files/styles/1280x720/public/2019-06/pretty-sky-concert.jpg")

Entry.create(title: "Ironing The Map", content: "Gastropub next level forage tbh messenger bag listicle. Stumptown williamsburg tbh la croix. Edison bulb la croix fixie kickstarter succulents woke tbh blog glossier bitters. VHS stumptown biodiesel, succulents pinterest hella flannel yr roof party aesthetic. Offal man bun 3 wolf moon polaroid neutra four loko chia small batch mlkshk single-origin coffee artisan. Yuccie vegan air plant, you probably haven't heard of them ethical mixtape neutra gastropub photo booth microdosing lo-fi.

Gochujang fashion axe thundercats man bun af vice, forage blue bottle migas austin XOXO swag squid taxidermy aesthetic. Jianbing cliche four loko readymade. Echo park before they sold out squid poke banjo XOXO pok pok 3 wolf moon direct trade meggings hammock portland. Pork belly fashion axe succulents, iceland irony green juice tumblr jianbing polaroid whatever you probably haven't heard of them chia meggings thundercats. Craft beer vegan pickled distillery asymmetrical, cloud bread fam bitters sustainable celiac YOLO PBR&B migas listicle letterpress. Vinyl deep v neutra, lumbersexual tacos schlitz +1 enamel pin bicycle rights slow-carb pug pabst gentrify jean shorts ethical.

Tofu pinterest la croix fam tilde. Bitters food truck shaman, humblebrag helvetica umami organic kombucha copper mug slow-carb roof party deep v. Put a bird on it post-ironic scenester jianbing microdosing. Artisan hashtag cornhole, tote bag migas deep v iceland chartreuse vinyl vape. Truffaut thundercats man bun cornhole.

Copper mug glossier pug, raclette literally etsy small batch twee. Williamsburg actually small batch, chambray health goth intelligentsia tote bag helvetica banjo. Slow-carb fingerstache poke, health goth craft beer lyft tbh. Austin pork belly offal cold-pressed. Swag sartorial lo-fi, tattooed knausgaard taxidermy ramps irony.

Kale chips roof party whatever typewriter, snackwave banh mi affogato truffaut. Master cleanse mixtape retro leggings four dollar toast swag man bun pok pok, fashion axe YOLO brooklyn skateboard. Slow-carb whatever tacos mumblecore paleo meh vape cronut. Cliche viral VHS, pok pok scenester green juice art party raw denim etsy blue bottle tattooed pickled. Twee cray cold-pressed banjo hot chicken.

Vegan street art migas lumbersexual man bun art party. Chartreuse knausgaard kombucha hammock. YOLO copper mug yuccie pop-up raw denim quinoa fashion axe chia twee irony scenester poutine wolf. Blog small batch meggings enamel pin intelligentsia. Put a bird on it kickstarter subway tile, cloud bread chia brooklyn la croix jianbing kogi tattooed. Put a bird on it meggings lomo tattooed quinoa freegan heirloom chia snackwave woke vegan fam letterpress distillery taxidermy. Af tumblr unicorn kitsch 3 wolf moon bushwick, tacos trust fund quinoa green juice gluten-free vexillologist meh man bun.

Williamsburg green juice kale chips, cred direct trade sustainable shabby chic scenester banh mi beard VHS tilde. Adaptogen raclette dreamcatcher art party, palo santo schlitz swag locavore iPhone la croix subway tile affogato hoodie selfies pinterest. Tousled tilde tbh seitan actually taxidermy. Disrupt thundercats hot chicken everyday carry. Vape poke butcher edison bulb keffiyeh chicharrones, gastropub fam wolf listicle deep v vinyl shoreditch thundercats. Dreamcatcher heirloom vegan jean shorts gentrify biodiesel occupy tofu craft beer meggings bushwick. Iceland everyday carry pug, asymmetrical farm-to-table put a bird on it sriracha taxidermy ennui godard yuccie single-origin coffee dreamcatcher activated charcoal.

Biodiesel kinfolk gastropub meggings, viral tousled slow-carb drinking vinegar. Tofu XOXO scenester, tilde 8-bit twee swag pinterest yr fingerstache williamsburg man braid raw denim coloring book squid. Hella tofu hexagon hoodie. Woke selfies umami shoreditch poutine marfa schlitz pop-up pok pok blog typewriter tattooed irony. Sriracha banjo paleo portland, meh pabst glossier leggings edison bulb. Trust fund small batch vegan pour-over bespoke, 8-bit kale chips iceland williamsburg you probably haven't heard of them cronut umami. Twee subway tile asymmetrical iceland raclette, art party swag literally.

Ethical pickled kale chips salvia, tumblr cray before they sold out pour-over selvage master cleanse. Jianbing glossier normcore meggings adaptogen, flannel marfa photo booth. Tumblr hexagon slow-carb cardigan truffaut jean shorts snackwave man braid shoreditch banjo street art farm-to-table cold-pressed polaroid enamel pin. Intelligentsia messenger bag pickled roof party viral cronut. Tattooed banh mi cronut austin beard. Hexagon keffiyeh cred activated charcoal tacos brunch jean shorts yr twee small batch tofu pabst XOXO franzen. Activated charcoal seitan pug four dollar toast synth pabst fam.", author_name: "Michael Scott", author_bio: "Distillery yuccie blog locavore. Hoodie mumblecore pop-up, helvetica ugh pabst sartorial. Ugh seitan DIY hot chicken truffaut. Flexitarian heirloom photo booth freegan kale chips meditation. Before they sold out semiotics 90's poke hexagon four loko pok pok freegan. Ramps green juice aesthetic freegan venmo 3 wolf moon tilde man braid pickled cloud bread PBR&B hell of franzen.", image: "https://kcbariatric.com/wp-content/uploads/2018/03/walking-elderly_wide-ee419df4ccf63bd563171e5292f3f94a47075055.jpg")

Entry.create(title: "Taking Things Around The Universe", content: "I'm baby gastropub synth organic godard mustache bitters normcore chicharrones occupy banjo. Brunch blog etsy, snackwave poutine migas cred tacos farm-to-table biodiesel unicorn copper mug readymade taiyaki. Yuccie shoreditch cred shabby chic aesthetic adaptogen ethical blue bottle locavore direct trade venmo tumeric squid cardigan hexagon. Mustache vaporware disrupt street art affogato keffiyeh. Fanny pack flannel af hashtag, retro small batch four dollar toast aesthetic kombucha whatever bespoke selfies readymade locavore. Wayfarers austin prism, lomo pok pok subway tile tote bag fam.

Fanny pack synth kitsch adaptogen waistcoat edison bulb. Franzen dreamcatcher tumeric, prism raw denim freegan plaid. Mlkshk truffaut ugh trust fund hot chicken. 3 wolf moon whatever poke, banh mi dreamcatcher actually messenger bag pug kogi wolf. Cardigan air plant everyday carry jianbing master cleanse yuccie banh mi tilde heirloom narwhal listicle austin iceland YOLO shabby chic. Kinfolk asymmetrical aesthetic tbh flexitarian forage cray kombucha dreamcatcher air plant try-hard.

Viral normcore chartreuse bushwick air plant put a bird on it kinfolk humblebrag vegan jianbing edison bulb bitters four dollar toast. Selfies fam poke, street art meggings pinterest vaporware la croix blue bottle cliche mustache. Microdosing mixtape dreamcatcher selvage, fashion axe sustainable readymade cray bespoke vape four loko jean shorts intelligentsia sartorial. Blog 8-bit +1 iPhone flannel narwhal.

Chartreuse shoreditch listicle venmo art party neutra mixtape you probably haven't heard of them kale chips roof party synth tattooed gastropub church-key VHS. Gochujang vaporware banh mi, selfies microdosing disrupt enamel pin lomo wayfarers put a bird on it hella schlitz iPhone pinterest woke. Gentrify post-ironic shabby chic, godard heirloom jianbing subway tile sartorial knausgaard plaid roof party. Shabby chic pok pok kitsch pug crucifix irony. Cold-pressed portland jean shorts succulents normcore activated charcoal artisan tattooed pop-up chambray. Sriracha art party gastropub banjo edison bulb blog chartreuse shabby chic four loko pitchfork.

Tattooed aesthetic umami, cloud bread echo park chambray subway tile. Chillwave yuccie leggings, schlitz tumblr readymade microdosing gluten-free pabst salvia. YOLO bespoke fixie disrupt tumblr occupy gluten-free gastropub tousled aesthetic. Pitchfork scenester offal art party, plaid sriracha chartreuse gochujang wayfarers dreamcatcher stumptown hell of quinoa franzen williamsburg.

Letterpress copper mug jean shorts gluten-free shaman viral man braid lomo. Hexagon tumblr organic, everyday carry pinterest tofu stumptown leggings semiotics kitsch. Pickled brunch four dollar toast wolf narwhal. Hella fashion axe vice, blog forage thundercats fingerstache cronut shabby chic drinking vinegar try-hard. Literally polaroid sustainable migas stumptown, intelligentsia neutra ennui snackwave pabst crucifix heirloom 3 wolf moon.

Squid before they sold out salvia kombucha pok pok prism, DIY vape venmo lumbersexual VHS la croix chartreuse. Vape ramps tofu waistcoat mustache. Butcher edison bulb meditation single-origin coffee pork belly. Lomo godard tacos raclette, selvage neutra hella photo booth cred direct trade. Shaman hot chicken bicycle rights keffiyeh, banjo single-origin coffee tbh chambray bitters lomo.", author_name: "Pam Beesly", author_bio: "Tousled humblebrag keytar, +1 cardigan gluten-free hammock lyft literally shaman banh mi single-origin coffee tote bag. Pork belly marfa migas roof party aesthetic vexillologist edison bulb artisan brunch post-ironic skateboard activated charcoal. Pitchfork hashtag ennui keffiyeh pug lomo cliche blue bottle. Lyft vape selfies, gochujang intelligentsia waistcoat locavore letterpress meggings. Hashtag fam kombucha art party drinking vinegar, salvia next level.", image: "https://i1.wp.com/digital-photography-school.com/wp-content/uploads/2017/08/Alto-Campoo-Ski-Lift-Milky-Way-e1502733284583.jpg")

Entry.create(title: "I'm Just a Messed Up Kid", content: "Aesthetic you probably haven't heard of them disrupt la croix. Everyday carry taxidermy disrupt polaroid truffaut. Raclette art party migas, pour-over subway tile humblebrag seitan yr pickled tattooed edison bulb hashtag. Disrupt glossier DIY cred. Meditation meh coloring book everyday carry, taiyaki authentic kickstarter.

Single-origin coffee tbh salvia glossier godard selfies meditation locavore hashtag. Selvage woke freegan heirloom literally mlkshk sartorial before they sold out enamel pin. Sriracha chillwave vinyl chartreuse you probably haven't heard of them affogato hella etsy four loko succulents. Single-origin coffee banh mi hashtag mustache.

Wayfarers cornhole offal art party hoodie intelligentsia. Sartorial tumblr helvetica neutra bushwick paleo tumeric tacos poke 3 wolf moon beard crucifix mumblecore succulents glossier. Lo-fi chartreuse copper mug brooklyn tote bag chicharrones shabby chic cronut quinoa neutra, austin cliche letterpress paleo vape. Thundercats air plant whatever sriracha messenger bag swag. Mixtape chillwave forage, tofu vegan godard viral subway tile ugh retro +1 tacos aesthetic skateboard. Gentrify microdosing kombucha, kitsch ugh letterpress craft beer cloud bread lyft. Kickstarter viral scenester thundercats meh you probably haven't heard of them.

Tumblr try-hard hexagon, shaman kale chips bicycle rights brooklyn. Franzen freegan small batch post-ironic messenger bag stumptown bicycle rights blue bottle letterpress you probably haven't heard of them try-hard cornhole live-edge 3 wolf moon. Trust fund celiac DIY yr drinking vinegar snackwave flexitarian gastropub typewriter freegan kombucha yuccie hammock tilde try-hard. Vinyl chambray portland iPhone quinoa. Ennui mumblecore knausgaard, 90's readymade asymmetrical flexitarian pinterest 3 wolf moon taxidermy direct trade godard meh. Flannel subway tile post-ironic kogi lyft cray bitters aesthetic cardigan intelligentsia yuccie bicycle rights.

Pitchfork meh irony letterpress scenester succulents beard gastropub migas quinoa. Woke selvage messenger bag, tbh shoreditch shabby chic hot chicken jianbing tote bag master cleanse bespoke pitchfork gentrify crucifix flexitarian. Mustache bitters flannel shabby chic godard pop-up etsy retro plaid tofu thundercats fashion axe letterpress vexillologist. Flexitarian adaptogen kombucha, schlitz unicorn disrupt enamel pin photo booth lomo selfies four dollar toast hammock marfa retro.

Tofu church-key organic tacos taiyaki vice. Portland crucifix blue bottle woke wayfarers deep v tousled, food truck cornhole scenester pop-up twee taiyaki bicycle rights cred. Shoreditch vice tumblr venmo, YOLO leggings microdosing quinoa narwhal tattooed jean shorts stumptown man bun. Echo park kickstarter hell of shabby chic microdosing wayfarers hammock. Helvetica raclette marfa activated charcoal VHS brooklyn echo park. Authentic four dollar toast 3 wolf moon copper mug chia tumblr. Stumptown YOLO celiac, art party aesthetic sartorial blog.

Fashion axe VHS selfies skateboard. Portland cliche neutra pug bespoke tousled, enamel pin put a bird on it farm-to-table coloring book cloud bread next level kogi af dreamcatcher. 90's drinking vinegar woke dreamcatcher. Street art squid gochujang, YOLO ethical dreamcatcher wayfarers coloring book. Four dollar toast salvia snackwave tattooed vaporware. Trust fund +1 hexagon subway tile, cray YOLO woke retro kickstarter brunch bitters crucifix sriracha craft beer hammock. Lomo chartreuse irony ugh.

Echo park butcher wayfarers, vexillologist meditation gentrify mixtape williamsburg. Wayfarers try-hard keffiyeh, pok pok pug schlitz raw denim intelligentsia 90's artisan gentrify leggings. Chambray vape poke mustache bespoke glossier thundercats banjo bitters shabby chic lo-fi blog fam kitsch intelligentsia. Listicle distillery meditation taiyaki, raw denim single-origin coffee seitan coloring book. Cronut yuccie gluten-free forage subway tile tumblr keffiyeh tote bag lo-fi deep v vexillologist selfies. Post-ironic meh la croix, pork belly lumbersexual raclette truffaut shoreditch lo-fi lomo food truck godard.

Plaid everyday carry polaroid umami waistcoat synth try-hard hammock direct trade cold-pressed thundercats godard four dollar toast gentrify four loko. Knausgaard ethical squid lyft, biodiesel swag ramps celiac tofu. Irony bespoke paleo man bun, poke listicle air plant occupy glossier viral retro venmo intelligentsia. Actually polaroid cronut pour-over lomo. Deep v pok pok listicle, brunch offal shabby chic tofu you probably haven't heard of them tbh health goth.

8-bit 3 wolf moon chambray, stumptown lomo photo booth wayfarers try-hard prism health goth cloud bread. Chillwave post-ironic chia iceland four loko. Cardigan artisan taiyaki, truffaut mixtape bicycle rights gluten-free aesthetic locavore brunch. Mixtape activated charcoal vinyl green juice, four dollar toast af chia mlkshk fingerstache. Vegan glossier small batch palo santo cred coloring book.", author_name: "Jim Halpert", author_bio: "Roof party williamsburg photo booth letterpress af heirloom kitsch occupy meggings taiyaki glossier hoodie trust fund brunch. Craft beer tumblr tumeric hammock. La croix whatever vice, chicharrones listicle street art ethical chia vaporware hexagon slow-carb hashtag. Iceland listicle williamsburg meditation squid occupy street art chicharrones.", image: "https://blogmedia.evbstatic.com/wp-content/uploads/wpmulti/sites/19/2016/11/Independent-in-live-music.jpg")

Entry.create(title: "Leave the Porch Light On", content: "Four dollar toast whatever semiotics franzen. La croix everyday carry asymmetrical fashion axe messenger bag gochujang forage locavore wayfarers you probably haven't heard of them kombucha cray disrupt. Raw denim cred listicle vegan, 3 wolf moon disrupt four loko blue bottle. Before they sold out 90's viral, williamsburg heirloom vaporware craft beer next level ennui fanny pack readymade.

Roof party fam freegan, 8-bit chia celiac activated charcoal ennui knausgaard helvetica VHS thundercats. Edison bulb celiac mlkshk photo booth sartorial ennui cliche VHS thundercats offal synth YOLO man bun raw denim. Hammock literally you probably haven't heard of them mixtape, biodiesel mustache marfa occupy echo park everyday carry yuccie quinoa. Seitan vexillologist leggings, tousled heirloom taiyaki ennui flexitarian chambray everyday carry cloud bread art party.

Hella thundercats roof party twee coloring book, pitchfork affogato. Irony palo santo copper mug, hashtag cronut listicle tattooed ethical ugh mustache vice pickled squid. Chambray wolf tumeric, hammock four dollar toast green juice bespoke scenester asymmetrical ethical unicorn roof party freegan. Pour-over beard chillwave meggings put a bird on it raw denim retro cornhole tacos whatever.

Pinterest marfa beard, shabby chic cronut 3 wolf moon plaid pop-up echo park salvia dreamcatcher man bun. Echo park quinoa jianbing gentrify. Normcore tacos authentic slow-carb gluten-free church-key taiyaki yuccie cardigan. PBR&B shabby chic polaroid, edison bulb humblebrag chia poutine craft beer hot chicken selvage cliche taiyaki.

Locavore umami kale chips meditation, gastropub schlitz irony PBR&B jianbing lo-fi. Semiotics fanny pack gochujang lo-fi. Freegan DIY small batch vaporware lyft green juice waistcoat fanny pack. Humblebrag literally yr, 3 wolf moon street art schlitz migas palo santo. Wolf pop-up activated charcoal tumblr, glossier vice plaid chambray readymade air plant. Hashtag dreamcatcher tbh, drinking vinegar fam direct trade food truck flannel mustache.

Activated charcoal bespoke affogato, crucifix four loko swag godard copper mug cornhole pitchfork poutine. Butcher air plant cardigan hell of, mustache single-origin coffee tacos microdosing farm-to-table cloud bread. Disrupt typewriter cronut, master cleanse slow-carb you probably haven't heard of them cold-pressed chicharrones wolf blue bottle pork belly vexillologist biodiesel knausgaard drinking vinegar. Sustainable vaporware everyday carry master cleanse neutra shaman, irony iceland intelligentsia kickstarter bicycle rights kogi actually next level. Polaroid snackwave plaid copper mug lyft. Twee chia keytar raw denim, blog poke plaid cold-pressed hot chicken ramps copper mug fixie. Portland truffaut hell of lomo snackwave everyday carry.

Mustache shaman locavore fixie raclette meh, chillwave pork belly DIY poke hexagon stumptown vinyl whatever. Unicorn kinfolk hexagon truffaut etsy kitsch. Ethical stumptown vaporware actually. Enamel pin post-ironic kickstarter, VHS disrupt fashion axe photo booth paleo next level. Mumblecore lumbersexual brooklyn, activated charcoal paleo vaporware gastropub fanny pack ethical mustache keytar pop-up. Tattooed franzen mixtape vice helvetica you probably haven't heard of them +1 asymmetrical pok pok hexagon.

Drinking vinegar yr everyday carry, kitsch bitters la croix occupy four dollar toast. Humblebrag poutine slow-carb tumblr pour-over bicycle rights normcore jean shorts offal meh literally blog subway tile polaroid. Pitchfork tousled glossier, venmo pop-up literally jianbing gentrify tumblr. Migas pabst kinfolk meh. Jean shorts sartorial cred pok pok craft beer gentrify four dollar toast lomo.", author_name: "Andy Bernard", author_bio: "Bicycle rights fam narwhal helvetica YOLO. Microdosing tumeric fashion axe, poutine adaptogen mlkshk chia iPhone celiac direct trade cronut subway tile squid. Aesthetic austin +1 semiotics man braid selfies, kickstarter VHS seitan cronut sustainable. Hella blog authentic, asymmetrical actually unicorn poutine whatever plaid lumbersexual subway tile copper mug shabby chic. Hammock mustache dreamcatcher, waistcoat heirloom 3 wolf moon hell of chillwave chartreuse raw denim wayfarers. 90's kale chips echo park everyday carry venmo pabst tote bag cold-pressed mlkshk.", image: "https://secure.i.telegraph.co.uk/multimedia/archive/02721/knitting_2721273b.jpg")

Entry.create(title: "Least of the Trains", content: "Aesthetic bespoke keytar migas. Truffaut vinyl VHS cardigan synth heirloom raclette jianbing tilde. Skateboard ethical pabst, swag sriracha banh mi green juice 8-bit you probably haven't heard of them. Meh sartorial vape raw denim jean shorts hell of 3 wolf moon next level paleo venmo twee. Locavore shabby chic synth tattooed. Taxidermy raclette kitsch, jianbing small batch leggings lumbersexual.

Raw denim tote bag poke locavore pug bicycle rights cred. Tousled flannel lo-fi woke migas plaid heirloom activated charcoal mlkshk air plant tacos raw denim edison bulb. Next level hexagon taiyaki chia migas. 8-bit meditation pop-up YOLO dreamcatcher quinoa yr iPhone irony vape hell of. Flannel tumblr chartreuse, cray single-origin coffee gastropub paleo gochujang fanny pack blue bottle church-key before they sold out prism. +1 drinking vinegar af taiyaki squid shaman echo park helvetica leggings intelligentsia whatever fam cronut cardigan kinfolk.

Deep v narwhal brooklyn pinterest, slow-carb try-hard coloring book chartreuse. Messenger bag disrupt selfies, bespoke enamel pin knausgaard gluten-free iPhone sriracha. Squid etsy tote bag jianbing mustache. Affogato sriracha retro deep v man braid whatever pork belly. Bushwick heirloom palo santo waistcoat raw denim, chambray activated charcoal poutine kogi adaptogen glossier hella prism. Kitsch put a bird on it pinterest, vice retro hammock cold-pressed chambray unicorn enamel pin edison bulb ramps +1 ugh.

Viral readymade kogi vice humblebrag. Plaid craft beer selvage flannel portland you probably haven't heard of them ennui, snackwave af post-ironic quinoa cardigan neutra meh hella. Polaroid chillwave lumbersexual pour-over schlitz truffaut man braid asymmetrical humblebrag keytar cornhole bespoke messenger bag banh mi. Ugh microdosing yuccie church-key portland. Offal disrupt kickstarter, pitchfork vexillologist bespoke banjo retro put a bird on it. Bicycle rights YOLO plaid, post-ironic gentrify echo park four loko aesthetic selfies tote bag franzen hella.

Unicorn dreamcatcher kale chips deep v, vegan try-hard blue bottle. Yuccie you probably haven't heard of them brunch, ramps raclette shaman mumblecore neutra air plant brooklyn celiac. Twee brunch cred, mixtape synth semiotics bicycle rights health goth brooklyn. Sriracha organic synth bespoke hella man braid hoodie. Keffiyeh edison bulb raw denim adaptogen, wayfarers flexitarian forage cronut green juice copper mug dreamcatcher hella 3 wolf moon migas.

Everyday carry vinyl paleo brunch tattooed, ethical kale chips slow-carb. Deep v chillwave adaptogen subway tile PBR&B single-origin coffee williamsburg scenester bespoke typewriter crucifix YOLO. Vegan PBR&B gentrify pabst. Green juice chicharrones flannel etsy tacos cloud bread pug direct trade sustainable offal truffaut brooklyn heirloom pinterest tousled.

Edison bulb microdosing scenester, tbh dreamcatcher bushwick jianbing vaporware kinfolk marfa tumblr aesthetic authentic. Tofu marfa everyday carry keffiyeh 3 wolf moon fixie vaporware narwhal green juice tote bag yuccie single-origin coffee hashtag kale chips. Hammock poke aesthetic offal. Letterpress copper mug taxidermy, distillery banjo kale chips chillwave everyday carry VHS squid tote bag.

Raw denim small batch +1 venmo, shabby chic viral DIY authentic man bun aesthetic. Tilde gluten-free tumblr raw denim hammock tbh vexillologist swag schlitz leggings wayfarers scenester. Aesthetic ugh normcore polaroid kitsch vaporware. Franzen celiac fanny pack synth crucifix pug bushwick sartorial wolf blue bottle succulents forage sriracha.", author_name: "Erin Hannon", author_bio: "Messenger bag crucifix art party, chambray cold-pressed direct trade 8-bit food truck sriracha kale chips paleo listicle lyft austin. Meggings listicle swag fashion axe flannel man bun typewriter activated charcoal kickstarter. Before they sold out chillwave skateboard, snackwave wayfarers kinfolk hashtag. Ramps hexagon vegan, cred freegan seitan venmo. Mustache vinyl ethical food truck brunch. Health goth cold-pressed pork belly hell of flexitarian prism seitan, bitters keffiyeh VHS tousled kale chips pour-over. Readymade air plant mustache, man bun lyft seitan sartorial hell of.", image: "https://www.pathwaystogod.org/sites/default/files/styles/banner/public/appletree.jpg")