Entry.create(title: "Find Your Way Home", content: "I'm baby fanny pack shabby chic listicle, hot chicken williamsburg hoodie yr austin enamel pin kinfolk selvage sustainable leggings taxidermy. Direct trade church-key edison bulb hexagon, trust fund lyft leggings unicorn pop-up iceland taxidermy salvia activated charcoal single-origin coffee woke. Brooklyn kombucha truffaut typewriter, tbh austin wayfarers asymmetrical lumbersexual DIY squid poutine single-origin coffee cred. Aesthetic polaroid man braid lo-fi, viral skateboard hammock vinyl try-hard farm-to-table echo park microdosing edison bulb craft beer banh mi. Vice echo park woke disrupt, raclette tousled marfa tofu photo booth fingerstache sartorial live-edge. Chicharrones ethical yuccie iPhone, everyday carry biodiesel tofu before they sold out celiac taxidermy austin. Pug vaporware single-origin coffee messenger bag jianbing gluten-free intelligentsia seitan.

Asymmetrical mustache pabst put a bird on it mumblecore flannel bespoke ennui lyft cray la croix cloud bread salvia vegan edison bulb. Ethical cliche selfies photo booth, portland shaman neutra lyft gochujang heirloom trust fund readymade. Listicle tilde activated charcoal authentic. Cliche succulents poke, iPhone food truck meditation celiac. Butcher authentic stumptown, godard adaptogen palo santo 3 wolf moon swag edison bulb letterpress thundercats taxidermy. Vinyl pinterest synth brooklyn cardigan.

3 wolf moon YOLO tbh, four dollar toast snackwave cred sartorial plaid adaptogen microdosing leggings hella bushwick post-ironic kale chips. Lyft irony actually, pork belly you probably haven't heard of them gochujang cray fashion axe williamsburg synth tote bag thundercats. Scenester kickstarter try-hard heirloom keytar sriracha asymmetrical vegan snackwave tumblr. Chia gastropub hashtag cloud bread wolf fashion axe kogi.

Yuccie chicharrones mumblecore hell of cred cliche beard gastropub direct trade craft beer marfa quinoa four dollar toast. Stumptown small batch umami photo booth brunch. Kinfolk vice biodiesel, snackwave retro DIY food truck tbh mustache freegan fixie. Heirloom mixtape vape XOXO typewriter banh mi intelligentsia. Hashtag whatever raclette synth edison bulb.

Everyday carry aesthetic franzen flexitarian narwhal listicle viral. Shoreditch lumbersexual whatever godard, raw denim etsy twee. Iceland semiotics master cleanse try-hard normcore. Palo santo thundercats lumbersexual swag. Gochujang photo booth raw denim tattooed microdosing twee food truck, woke lomo tote bag. Tote bag gluten-free mlkshk lomo, tofu VHS pok pok fam chillwave man braid hashtag hot chicken.", author_name: "Erin Branzell", author_bio: "Irony post-ironic snackwave, drinking vinegar glossier narwhal neutra. Bicycle rights edison bulb meh, helvetica next level pok pok single-origin coffee raw denim shaman iceland aesthetic adaptogen marfa. Messenger bag knausgaard vape artisan pinterest echo park asymmetrical craft beer tbh. Hell of authentic sustainable lo-fi narwhal echo park. 3 wolf moon tote bag enamel pin lyft, four dollar toast wolf blue bottle. Umami hot chicken cold-pressed unicorn viral truffaut.", image: "https://cdn.britannica.com/27/131227-004-A04CCC40/snail.jpg")

Entry.create(title: "Running In Place", content: "Hexagon crucifix tote bag, venmo freegan before they sold out XOXO raclette put a bird on it bicycle rights tofu blue bottle hashtag. Vexillologist art party twee chartreuse. Single-origin coffee mustache raclette swag shabby chic normcore. Swag ugh you probably haven't heard of them, salvia fanny pack tacos umami selvage. Adaptogen post-ironic hoodie small batch wolf pug plaid meh fanny pack normcore cardigan iceland lo-fi paleo tumeric. Gochujang heirloom meh hashtag ugh.

Venmo stumptown sustainable pinterest man braid bespoke umami beard blog iceland flexitarian. Hot chicken you probably haven't heard of them normcore artisan offal bicycle rights, tacos narwhal vape yr +1 shabby chic single-origin coffee. Food truck roof party chillwave, health goth PBR&B jean shorts succulents franzen unicorn chartreuse truffaut farm-to-table. Pitchfork ennui enamel pin 90's.

Jean shorts selvage gentrify everyday carry artisan. Butcher selvage disrupt vegan meggings occupy bespoke cardigan. Humblebrag adaptogen pitchfork, freegan umami pabst mustache dreamcatcher. Humblebrag church-key hashtag air plant vape tousled sustainable aesthetic forage. Blue bottle iceland 8-bit woke, jianbing +1 truffaut yr YOLO snackwave tbh vaporware heirloom. Retro hell of chicharrones, ugh poke adaptogen helvetica viral hot chicken master cleanse palo santo.

Literally narwhal iPhone vaporware XOXO truffaut try-hard 8-bit meh austin neutra YOLO. Man braid gochujang blue bottle health goth, XOXO biodiesel synth flannel bespoke farm-to-table iPhone. Shabby chic tumblr prism beard literally, tofu DIY wayfarers. Hot chicken dreamcatcher bitters gluten-free, banh mi letterpress flannel wolf enamel pin tbh jean shorts. Banjo meggings man bun shoreditch tacos hot chicken. Aesthetic poke pork belly tumeric. Blog forage chillwave, vice church-key try-hard direct trade hashtag health goth offal lo-fi slow-carb echo park marfa actually.", author_name: "Doug Schallmoser", author_bio: "Distillery yuccie blog locavore. Hoodie mumblecore pop-up, helvetica ugh pabst sartorial. Ugh seitan DIY hot chicken truffaut. Flexitarian heirloom photo booth freegan kale chips meditation. Before they sold out semiotics 90's poke hexagon four loko pok pok freegan. Ramps green juice aesthetic freegan venmo 3 wolf moon tilde man braid pickled cloud bread PBR&B hell of franzen.", image: "https://static.inaturalist.org/photos/13134367/large.jpg")

Entry.create(title: "Simplicity Sake", content: "I'm baby fanny pack shabby chic listicle, hot chicken williamsburg hoodie yr austin enamel pin kinfolk selvage sustainable leggings taxidermy. Direct trade church-key edison bulb hexagon, trust fund lyft leggings unicorn pop-up iceland taxidermy salvia activated charcoal single-origin coffee woke. Brooklyn kombucha truffaut typewriter, tbh austin wayfarers asymmetrical lumbersexual DIY squid poutine single-origin coffee cred. Aesthetic polaroid man braid lo-fi, viral skateboard hammock vinyl try-hard farm-to-table echo park microdosing edison bulb craft beer banh mi. Vice echo park woke disrupt, raclette tousled marfa tofu photo booth fingerstache sartorial live-edge. Chicharrones ethical yuccie iPhone, everyday carry biodiesel tofu before they sold out celiac taxidermy austin. Pug vaporware single-origin coffee messenger bag jianbing gluten-free intelligentsia seitan.

Asymmetrical mustache pabst put a bird on it mumblecore flannel bespoke ennui lyft cray la croix cloud bread salvia vegan edison bulb. Ethical cliche selfies photo booth, portland shaman neutra lyft gochujang heirloom trust fund readymade. Listicle tilde activated charcoal authentic. Cliche succulents poke, iPhone food truck meditation celiac. Butcher authentic stumptown, godard adaptogen palo santo 3 wolf moon swag edison bulb letterpress thundercats taxidermy. Vinyl pinterest synth brooklyn cardigan.

3 wolf moon YOLO tbh, four dollar toast snackwave cred sartorial plaid adaptogen microdosing leggings hella bushwick post-ironic kale chips. Lyft irony actually, pork belly you probably haven't heard of them gochujang cray fashion axe williamsburg synth tote bag thundercats. Scenester kickstarter try-hard heirloom keytar sriracha asymmetrical vegan snackwave tumblr. Chia gastropub hashtag cloud bread wolf fashion axe kogi.

Yuccie chicharrones mumblecore hell of cred cliche beard gastropub direct trade craft beer marfa quinoa four dollar toast. Stumptown small batch umami photo booth brunch. Kinfolk vice biodiesel, snackwave retro DIY food truck tbh mustache freegan fixie. Heirloom mixtape vape XOXO typewriter banh mi intelligentsia. Hashtag whatever raclette synth edison bulb.

Everyday carry aesthetic franzen flexitarian narwhal listicle viral. Shoreditch lumbersexual whatever godard, raw denim etsy twee. Iceland semiotics master cleanse try-hard normcore. Palo santo thundercats lumbersexual swag. Gochujang photo booth raw denim tattooed microdosing twee food truck, woke lomo tote bag. Tote bag gluten-free mlkshk lomo, tofu VHS pok pok fam chillwave man braid hashtag hot chicken.", author_name: "Doug Schallmoser", author_bio: "Distillery yuccie blog locavore. Hoodie mumblecore pop-up, helvetica ugh pabst sartorial. Ugh seitan DIY hot chicken truffaut. Flexitarian heirloom photo booth freegan kale chips meditation. Before they sold out semiotics 90's poke hexagon four loko pok pok freegan. Ramps green juice aesthetic freegan venmo 3 wolf moon tilde man braid pickled cloud bread PBR&B hell of franzen.", image: "https://www.dgs.udel.edu/sites/default/files/styles/max_650x650/public/geohydro/fossils-orange_slug.jpg")

Entry.create(title: "Woods and Glaciers", content: "I'm baby coloring book next level authentic mumblecore hexagon. Try-hard listicle enamel pin, mixtape slow-carb squid hammock polaroid retro celiac sriracha tbh af. Raclette freegan taxidermy next level vinyl messenger bag. Bushwick stumptown yr, poutine plaid locavore schlitz glossier live-edge scenester.

Four loko taiyaki poutine health goth. Humblebrag distillery tattooed woke tumeric godard tbh cronut tilde health goth. Literally flexitarian offal farm-to-table squid, knausgaard schlitz brunch. Chillwave tofu pug keffiyeh shabby chic tumeric offal taiyaki health goth sartorial bicycle rights. Taxidermy artisan four dollar toast la croix, bushwick trust fund kickstarter live-edge kitsch ramps vegan gochujang. Lyft cray subway tile banjo la croix next level.

Four dollar toast jianbing butcher, godard hammock raclette flannel pickled irony wolf church-key cornhole fixie quinoa. Schlitz tbh edison bulb, tofu chicharrones blue bottle pok pok lo-fi hell of. Pinterest helvetica edison bulb cray literally freegan before they sold out you probably haven't heard of them keytar art party pour-over trust fund. Listicle XOXO narwhal celiac yuccie. Direct trade semiotics cornhole glossier mlkshk migas irony. Hell of bitters biodiesel fashion axe put a bird on it jianbing next level echo park butcher.

Kale chips listicle enamel pin biodiesel salvia hammock. Church-key kombucha art party, meditation lo-fi hashtag 90's gentrify la croix. Single-origin coffee pok pok distillery cred, swag franzen gentrify cliche kombucha. Iceland schlitz deep v iPhone retro selvage, pinterest venmo normcore banjo wayfarers actually gastropub. Vice franzen portland meh cornhole vaporware.

Pok pok next level locavore mumblecore keffiyeh hexagon sustainable yuccie cornhole ramps prism iPhone skateboard. Af banjo wolf hella meggings sriracha marfa food truck gluten-free church-key plaid bespoke. Tbh mumblecore listicle kombucha, scenester edison bulb iPhone freegan activated charcoal brooklyn cliche plaid. Godard direct trade glossier 90's YOLO typewriter tote bag occupy kogi lyft wayfarers. Lomo kogi echo park, normcore tofu flannel +1 gochujang ennui everyday carry disrupt four dollar toast stumptown dreamcatcher. Forage farm-to-table ennui knausgaard paleo portland 8-bit.

Ennui cloud bread semiotics cold-pressed, hella vaporware drinking vinegar farm-to-table whatever shaman plaid skateboard portland helvetica. Shaman vinyl yr edison bulb, whatever tousled kale chips you probably haven't heard of them taxidermy four loko seitan la croix iPhone microdosing poke. Ennui kale chips 3 wolf moon, bespoke forage twee brunch pour-over. Activated charcoal chillwave retro street art squid meh. Organic kinfolk trust fund tumblr.

Cronut before they sold out try-hard sustainable knausgaard. Vinyl offal pour-over, copper mug vegan austin jianbing kombucha keytar. Hashtag chicharrones green juice celiac put a bird on it pitchfork. Meggings la croix knausgaard, twee hella migas chicharrones umami. 3 wolf moon shabby chic tilde, ugh thundercats etsy affogato ramps keytar locavore man braid actually scenester literally hella. Wolf four loko man braid craft beer, cornhole green juice poutine tofu hammock bitters literally tote bag church-key. Tote bag XOXO jean shorts leggings, palo santo literally lyft synth normcore.

Humblebrag direct trade palo santo pork belly. Four dollar toast food truck tilde disrupt. Fingerstache 90's beard actually, kogi aesthetic hammock kombucha banjo cloud bread pop-up. Semiotics shabby chic tbh before they sold out pabst yr roof party pour-over sartorial mumblecore humblebrag. Pork belly meditation cloud bread, selvage woke waistcoat chillwave tote bag sartorial vexillologist microdosing chartreuse. Retro 90's tumeric ennui health goth typewriter poutine iceland schlitz. Blog intelligentsia trust fund cornhole, typewriter forage everyday carry.", author_name: "Sam Johnson", author_bio: "Blog chillwave asymmetrical chartreuse wolf pork belly kale chips 3 wolf moon YOLO gochujang hell of. Vaporware 3 wolf moon shoreditch, hell of four loko ethical fashion axe bushwick keffiyeh vegan. Stumptown swag slow-carb fixie chillwave master cleanse. Jean shorts knausgaard cardigan, venmo cloud bread keffiyeh taxidermy. Selvage ennui waistcoat roof party tumblr.", image: "https://i.pinimg.com/originals/c6/a6/7f/c6a67f297ebc480f1f85b3ca847225bb.jpg")

Entry.create(title: "Ironing The Map", content: "Gastropub next level forage tbh messenger bag listicle. Stumptown williamsburg tbh la croix. Edison bulb la croix fixie kickstarter succulents woke tbh blog glossier bitters. VHS stumptown biodiesel, succulents pinterest hella flannel yr roof party aesthetic. Offal man bun 3 wolf moon polaroid neutra four loko chia small batch mlkshk single-origin coffee artisan. Yuccie vegan air plant, you probably haven't heard of them ethical mixtape neutra gastropub photo booth microdosing lo-fi.

Gochujang fashion axe thundercats man bun af vice, forage blue bottle migas austin XOXO swag squid taxidermy aesthetic. Jianbing cliche four loko readymade. Echo park before they sold out squid poke banjo XOXO pok pok 3 wolf moon direct trade meggings hammock portland. Pork belly fashion axe succulents, iceland irony green juice tumblr jianbing polaroid whatever you probably haven't heard of them chia meggings thundercats. Craft beer vegan pickled distillery asymmetrical, cloud bread fam bitters sustainable celiac YOLO PBR&B migas listicle letterpress. Vinyl deep v neutra, lumbersexual tacos schlitz +1 enamel pin bicycle rights slow-carb pug pabst gentrify jean shorts ethical.

Tofu pinterest la croix fam tilde. Bitters food truck shaman, humblebrag helvetica umami organic kombucha copper mug slow-carb roof party deep v. Put a bird on it post-ironic scenester jianbing microdosing. Artisan hashtag cornhole, tote bag migas deep v iceland chartreuse vinyl vape. Truffaut thundercats man bun cornhole.

Copper mug glossier pug, raclette literally etsy small batch twee. Williamsburg actually small batch, chambray health goth intelligentsia tote bag helvetica banjo. Slow-carb fingerstache poke, health goth craft beer lyft tbh. Austin pork belly offal cold-pressed. Swag sartorial lo-fi, tattooed knausgaard taxidermy ramps irony.

Kale chips roof party whatever typewriter, snackwave banh mi affogato truffaut. Master cleanse mixtape retro leggings four dollar toast swag man bun pok pok, fashion axe YOLO brooklyn skateboard. Slow-carb whatever tacos mumblecore paleo meh vape cronut. Cliche viral VHS, pok pok scenester green juice art party raw denim etsy blue bottle tattooed pickled. Twee cray cold-pressed banjo hot chicken.

Vegan street art migas lumbersexual man bun art party. Chartreuse knausgaard kombucha hammock. YOLO copper mug yuccie pop-up raw denim quinoa fashion axe chia twee irony scenester poutine wolf. Blog small batch meggings enamel pin intelligentsia. Put a bird on it kickstarter subway tile, cloud bread chia brooklyn la croix jianbing kogi tattooed. Put a bird on it meggings lomo tattooed quinoa freegan heirloom chia snackwave woke vegan fam letterpress distillery taxidermy. Af tumblr unicorn kitsch 3 wolf moon bushwick, tacos trust fund quinoa green juice gluten-free vexillologist meh man bun.

Williamsburg green juice kale chips, cred direct trade sustainable shabby chic scenester banh mi beard VHS tilde. Adaptogen raclette dreamcatcher art party, palo santo schlitz swag locavore iPhone la croix subway tile affogato hoodie selfies pinterest. Tousled tilde tbh seitan actually taxidermy. Disrupt thundercats hot chicken everyday carry. Vape poke butcher edison bulb keffiyeh chicharrones, gastropub fam wolf listicle deep v vinyl shoreditch thundercats. Dreamcatcher heirloom vegan jean shorts gentrify biodiesel occupy tofu craft beer meggings bushwick. Iceland everyday carry pug, asymmetrical farm-to-table put a bird on it sriracha taxidermy ennui godard yuccie single-origin coffee dreamcatcher activated charcoal.

Biodiesel kinfolk gastropub meggings, viral tousled slow-carb drinking vinegar. Tofu XOXO scenester, tilde 8-bit twee swag pinterest yr fingerstache williamsburg man braid raw denim coloring book squid. Hella tofu hexagon hoodie. Woke selfies umami shoreditch poutine marfa schlitz pop-up pok pok blog typewriter tattooed irony. Sriracha banjo paleo portland, meh pabst glossier leggings edison bulb. Trust fund small batch vegan pour-over bespoke, 8-bit kale chips iceland williamsburg you probably haven't heard of them cronut umami. Twee subway tile asymmetrical iceland raclette, art party swag literally.

Ethical pickled kale chips salvia, tumblr cray before they sold out pour-over selvage master cleanse. Jianbing glossier normcore meggings adaptogen, flannel marfa photo booth. Tumblr hexagon slow-carb cardigan truffaut jean shorts snackwave man braid shoreditch banjo street art farm-to-table cold-pressed polaroid enamel pin. Intelligentsia messenger bag pickled roof party viral cronut. Tattooed banh mi cronut austin beard. Hexagon keffiyeh cred activated charcoal tacos brunch jean shorts yr twee small batch tofu pabst XOXO franzen. Activated charcoal seitan pug four dollar toast synth pabst fam.", author_name: "Michael Scott", author_bio: "Distillery yuccie blog locavore. Hoodie mumblecore pop-up, helvetica ugh pabst sartorial. Ugh seitan DIY hot chicken truffaut. Flexitarian heirloom photo booth freegan kale chips meditation. Before they sold out semiotics 90's poke hexagon four loko pok pok freegan. Ramps green juice aesthetic freegan venmo 3 wolf moon tilde man braid pickled cloud bread PBR&B hell of franzen.", image: "https://i.pinimg.com/originals/39/e5/71/39e571387539ba90a43e6f7f81e74767.jpg")