Entry.create(title: "Find Your Way Home", content: "I'm baby fanny pack shabby chic listicle, hot chicken williamsburg hoodie yr austin enamel pin kinfolk selvage sustainable leggings taxidermy. Direct trade church-key edison bulb hexagon, trust fund lyft leggings unicorn pop-up iceland taxidermy salvia activated charcoal single-origin coffee woke. Brooklyn kombucha truffaut typewriter, tbh austin wayfarers asymmetrical lumbersexual DIY squid poutine single-origin coffee cred. Aesthetic polaroid man braid lo-fi, viral skateboard hammock vinyl try-hard farm-to-table echo park microdosing edison bulb craft beer banh mi. Vice echo park woke disrupt, raclette tousled marfa tofu photo booth fingerstache sartorial live-edge. Chicharrones ethical yuccie iPhone, everyday carry biodiesel tofu before they sold out celiac taxidermy austin. Pug vaporware single-origin coffee messenger bag jianbing gluten-free intelligentsia seitan.

Asymmetrical mustache pabst put a bird on it mumblecore flannel bespoke ennui lyft cray la croix cloud bread salvia vegan edison bulb. Ethical cliche selfies photo booth, portland shaman neutra lyft gochujang heirloom trust fund readymade. Listicle tilde activated charcoal authentic. Cliche succulents poke, iPhone food truck meditation celiac. Butcher authentic stumptown, godard adaptogen palo santo 3 wolf moon swag edison bulb letterpress thundercats taxidermy. Vinyl pinterest synth brooklyn cardigan.

3 wolf moon YOLO tbh, four dollar toast snackwave cred sartorial plaid adaptogen microdosing leggings hella bushwick post-ironic kale chips. Lyft irony actually, pork belly you probably haven't heard of them gochujang cray fashion axe williamsburg synth tote bag thundercats. Scenester kickstarter try-hard heirloom keytar sriracha asymmetrical vegan snackwave tumblr. Chia gastropub hashtag cloud bread wolf fashion axe kogi.

Yuccie chicharrones mumblecore hell of cred cliche beard gastropub direct trade craft beer marfa quinoa four dollar toast. Stumptown small batch umami photo booth brunch. Kinfolk vice biodiesel, snackwave retro DIY food truck tbh mustache freegan fixie. Heirloom mixtape vape XOXO typewriter banh mi intelligentsia. Hashtag whatever raclette synth edison bulb.

Everyday carry aesthetic franzen flexitarian narwhal listicle viral. Shoreditch lumbersexual whatever godard, raw denim etsy twee. Iceland semiotics master cleanse try-hard normcore. Palo santo thundercats lumbersexual swag. Gochujang photo booth raw denim tattooed microdosing twee food truck, woke lomo tote bag. Tote bag gluten-free mlkshk lomo, tofu VHS pok pok fam chillwave man braid hashtag hot chicken.", author_name: "Erin Branzell", author_bio: "Irony post-ironic snackwave, drinking vinegar glossier narwhal neutra. Bicycle rights edison bulb meh, helvetica next level pok pok single-origin coffee raw denim shaman iceland aesthetic adaptogen marfa. Messenger bag knausgaard vape artisan pinterest echo park asymmetrical craft beer tbh. Hell of authentic sustainable lo-fi narwhal echo park. 3 wolf moon tote bag enamel pin lyft, four dollar toast wolf blue bottle. Umami hot chicken cold-pressed unicorn viral truffaut.")

Entry.create(title: "Running In Place", content: "Hexagon crucifix tote bag, venmo freegan before they sold out XOXO raclette put a bird on it bicycle rights tofu blue bottle hashtag. Vexillologist art party twee chartreuse. Single-origin coffee mustache raclette swag shabby chic normcore. Swag ugh you probably haven't heard of them, salvia fanny pack tacos umami selvage. Adaptogen post-ironic hoodie small batch wolf pug plaid meh fanny pack normcore cardigan iceland lo-fi paleo tumeric. Gochujang heirloom meh hashtag ugh.

Venmo stumptown sustainable pinterest man braid bespoke umami beard blog iceland flexitarian. Hot chicken you probably haven't heard of them normcore artisan offal bicycle rights, tacos narwhal vape yr +1 shabby chic single-origin coffee. Food truck roof party chillwave, health goth PBR&B jean shorts succulents franzen unicorn chartreuse truffaut farm-to-table. Pitchfork ennui enamel pin 90's.

Jean shorts selvage gentrify everyday carry artisan. Butcher selvage disrupt vegan meggings occupy bespoke cardigan. Humblebrag adaptogen pitchfork, freegan umami pabst mustache dreamcatcher. Humblebrag church-key hashtag air plant vape tousled sustainable aesthetic forage. Blue bottle iceland 8-bit woke, jianbing +1 truffaut yr YOLO snackwave tbh vaporware heirloom. Retro hell of chicharrones, ugh poke adaptogen helvetica viral hot chicken master cleanse palo santo.

Literally narwhal iPhone vaporware XOXO truffaut try-hard 8-bit meh austin neutra YOLO. Man braid gochujang blue bottle health goth, XOXO biodiesel synth flannel bespoke farm-to-table iPhone. Shabby chic tumblr prism beard literally, tofu DIY wayfarers. Hot chicken dreamcatcher bitters gluten-free, banh mi letterpress flannel wolf enamel pin tbh jean shorts. Banjo meggings man bun shoreditch tacos hot chicken. Aesthetic poke pork belly tumeric. Blog forage chillwave, vice church-key try-hard direct trade hashtag health goth offal lo-fi slow-carb echo park marfa actually.", author_name: "Doug Schallmoser", author_bio: "Distillery yuccie blog locavore. Hoodie mumblecore pop-up, helvetica ugh pabst sartorial. Ugh seitan DIY hot chicken truffaut. Flexitarian heirloom photo booth freegan kale chips meditation. Before they sold out semiotics 90's poke hexagon four loko pok pok freegan. Ramps green juice aesthetic freegan venmo 3 wolf moon tilde man braid pickled cloud bread PBR&B hell of franzen.")

Entry.create(title: "Simplicity Sake", content: "I'm baby fanny pack shabby chic listicle, hot chicken williamsburg hoodie yr austin enamel pin kinfolk selvage sustainable leggings taxidermy. Direct trade church-key edison bulb hexagon, trust fund lyft leggings unicorn pop-up iceland taxidermy salvia activated charcoal single-origin coffee woke. Brooklyn kombucha truffaut typewriter, tbh austin wayfarers asymmetrical lumbersexual DIY squid poutine single-origin coffee cred. Aesthetic polaroid man braid lo-fi, viral skateboard hammock vinyl try-hard farm-to-table echo park microdosing edison bulb craft beer banh mi. Vice echo park woke disrupt, raclette tousled marfa tofu photo booth fingerstache sartorial live-edge. Chicharrones ethical yuccie iPhone, everyday carry biodiesel tofu before they sold out celiac taxidermy austin. Pug vaporware single-origin coffee messenger bag jianbing gluten-free intelligentsia seitan.

Asymmetrical mustache pabst put a bird on it mumblecore flannel bespoke ennui lyft cray la croix cloud bread salvia vegan edison bulb. Ethical cliche selfies photo booth, portland shaman neutra lyft gochujang heirloom trust fund readymade. Listicle tilde activated charcoal authentic. Cliche succulents poke, iPhone food truck meditation celiac. Butcher authentic stumptown, godard adaptogen palo santo 3 wolf moon swag edison bulb letterpress thundercats taxidermy. Vinyl pinterest synth brooklyn cardigan.

3 wolf moon YOLO tbh, four dollar toast snackwave cred sartorial plaid adaptogen microdosing leggings hella bushwick post-ironic kale chips. Lyft irony actually, pork belly you probably haven't heard of them gochujang cray fashion axe williamsburg synth tote bag thundercats. Scenester kickstarter try-hard heirloom keytar sriracha asymmetrical vegan snackwave tumblr. Chia gastropub hashtag cloud bread wolf fashion axe kogi.

Yuccie chicharrones mumblecore hell of cred cliche beard gastropub direct trade craft beer marfa quinoa four dollar toast. Stumptown small batch umami photo booth brunch. Kinfolk vice biodiesel, snackwave retro DIY food truck tbh mustache freegan fixie. Heirloom mixtape vape XOXO typewriter banh mi intelligentsia. Hashtag whatever raclette synth edison bulb.

Everyday carry aesthetic franzen flexitarian narwhal listicle viral. Shoreditch lumbersexual whatever godard, raw denim etsy twee. Iceland semiotics master cleanse try-hard normcore. Palo santo thundercats lumbersexual swag. Gochujang photo booth raw denim tattooed microdosing twee food truck, woke lomo tote bag. Tote bag gluten-free mlkshk lomo, tofu VHS pok pok fam chillwave man braid hashtag hot chicken.", author_name: "Doug Schallmoser", author_bio: "Distillery yuccie blog locavore. Hoodie mumblecore pop-up, helvetica ugh pabst sartorial. Ugh seitan DIY hot chicken truffaut. Flexitarian heirloom photo booth freegan kale chips meditation. Before they sold out semiotics 90's poke hexagon four loko pok pok freegan. Ramps green juice aesthetic freegan venmo 3 wolf moon tilde man braid pickled cloud bread PBR&B hell of franzen.")